# Generated by Django 6.0.3 on 2026-03-14 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=20)),
                ('enable_ai_remediation', models.BooleanField(default=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('zap_api_key', models.CharField(blank=True, max_length=255)),
                ('zap_proxy_url', models.CharField(default='http://localhost:8080', max_length=255)),
                ('email_notifications', models.BooleanField(default=True)),
                ('scan_complete_alerts', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
