# Generated by Django 6.0.3 on 2026-03-14 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_alter_scan_scan_type_vulnerability'),
        ('targets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='current_phase',
            field=models.CharField(blank=True, default='Pending...', max_length=255),
        ),
        migrations.AddField(
            model_name='scan',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cwe_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cwe_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='CWE ID'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='owasp_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(choices=[('nmap', 'Network Scan (Nmap)'), ('nikto', 'Web Vulnerability Scan (Nikto)'), ('gobuster', 'Directory Bruteforce (Gobuster)'), ('zap', 'Web Scan (OWASP ZAP)'), ('nuclei', 'Vulnerability Scan (Nuclei)'), ('custom', 'Custom Script')], default='nmap', max_length=20),
        ),
        migrations.CreateModel(
            name='OWASPScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.target')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OWASPAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.CharField(max_length=255)),
                ('risk', models.CharField(max_length=50)),
                ('reliability', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=1000)),
                ('description', models.TextField()),
                ('solution', models.TextField()),
                ('param', models.CharField(blank=True, max_length=255)),
                ('evidence', models.TextField(blank=True)),
                ('cweid', models.CharField(blank=True, max_length=50)),
                ('wascid', models.CharField(blank=True, max_length=50)),
                ('owasp_category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owasp_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='scans.owaspscan')),
            ],
        ),
    ]
