# Generated by Django 6.0.3 on 2026-03-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_report'),
        ('scans', '0004_vulnerability_cvss_score_vulnerability_cvss_vector_and_more'),
    ]

    operations = [
    ]
