# Generated by Django 6.0.3 on 2026-03-14 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_merge_20260314_1414'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='report',
            name='filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('executive', 'Executive Summary'), ('technical', 'Technical Report'), ('compliance_pci', 'PCI-DSS Compliance'), ('compliance_iso', 'ISO 27001 Compliance')], default='technical', max_length=20),
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_range', models.CharField(choices=[('all_scans', 'All Scans Data'), ('all_vulns', 'All Vulnerabilities'), ('filtered', 'Filtered Data')], default='filtered', max_length=20)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('excel', 'Excel (XLSX)')], default='csv', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('fields_selection', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
