# Generated by Django 6.0.3 on 2026-03-14 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        ('scans', '0004_vulnerability_cvss_score_vulnerability_cvss_vector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('html_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('owasp_alert', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_remediation', to='scans.owaspalert')),
                ('vulnerability', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_remediation', to='scans.vulnerability')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
